(() => {
  'use strict';
  const client = window.nabdSupabase;
  const $ = selector => document.querySelector(selector);
  const grid = $('#premiumGrid');
  const title = $('#premiumViewTitle');
  const description = $('#premiumViewDescription');
  const back = $('#premiumBack');
  const state = { level: 'branch', branch: null, teacher: null, subject: null, records: [] };
  const escapeHTML = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const iconFor = (level, value = '') => level === 'branch' ? (value === 'literary' ? 'fa-feather-pointed' : 'fa-flask') : level === 'teacher' ? 'fa-chalkboard-user' : level === 'subject' ? 'fa-book-open' : 'fa-file-lines';
  const toast = text => { const node = $('#toast'); if (!node) return; node.textContent = text; node.classList.add('show'); clearTimeout(window.premiumToastTimer); window.premiumToastTimer = setTimeout(() => node.classList.remove('show'), 3000); };
  const friendlyError = (error, fallback) => { const message = String(error?.message || '').trim(); if (/invalid api key|permission denied|jwt|failed to fetch|networkerror|network request/i.test(message.toLowerCase())) return 'تعذر الاتصال بمحتوى القسم المميز حاليًا. تحقق من الاتصال ثم حاول مرة أخرى.'; return message || fallback; };
  const cacheKey = (name, args = {}) => `nabd_premium_cache_${name}_${encodeURIComponent(JSON.stringify(args))}`;
  const readCache = (name, args = {}) => { try { const raw = localStorage.getItem(cacheKey(name, args)); if (raw === null) return null; const parsed = JSON.parse(raw); return Array.isArray(parsed) ? parsed : null; } catch { return null; } };
  const writeCache = (name, args, data) => { try { localStorage.setItem(cacheKey(name, args), JSON.stringify(data)); } catch { /* التخزين المحلي اختياري */ } };
  const rpc = async (name, args = {}) => { if (!client) throw new Error('تحتاج هذه العملية إلى اتصال.'); const result = await client.rpc(name, args); if (result.error) throw result.error; const data = result.data || []; writeCache(name, args, data); return data; };
  const setLoading = () => { grid.innerHTML = '<div class="premium-empty"><i class="fa-solid fa-spinner fa-spin"></i><h3>جارٍ تحميل المحتوى</h3><p>نجهز لك الخيارات المتاحة.</p></div>'; };
  const setEmpty = (heading, note) => { grid.innerHTML = `<div class="premium-empty"><i class="fa-regular fa-folder-open"></i><h3>${escapeHTML(heading)}</h3><p>${escapeHTML(note)}</p></div>`; };
  const modal = () => ({ backdrop: $('#modalBackdrop'), content: $('#modalContent') });
  let modalHistoryEntry = false;
  const closeModal = () => { const { backdrop } = modal(); const shouldRestoreHistory = modalHistoryEntry; modalHistoryEntry = false; backdrop?.classList.remove('show'); document.body.classList.remove('sheet-open'); if (shouldRestoreHistory && history.state?.premiumModal === 'access') history.back(); };
  const openModal = content => { const { backdrop, content: target } = modal(); if (!backdrop || !target) return; target.innerHTML = content; backdrop.classList.add('show'); document.body.classList.add('sheet-open'); const closeButton = target.querySelector('.close-modal'); closeButton?.addEventListener('click', event => { event.stopPropagation(); closeModal(); }); closeButton?.focus(); };
  const whatsappHref = (number, text) => { const digits = String(number || '').replace(/[^0-9]/g, ''); return digits ? `https://wa.me/${digits}?text=${encodeURIComponent(text)}` : ''; };
  const updateSteps = () => { document.querySelectorAll('[data-premium-step]').forEach(step => step.classList.toggle('active', step.dataset.premiumStep === state.level)); back?.classList.toggle('hidden', state.level === 'branch'); };
  const card = (level, item, subtitle, extra = '') => `<button class="premium-card ${level === 'file' ? 'premium-file-card' : ''}" type="button" data-premium-id="${escapeHTML(item.id)}"><span class="premium-card-icon"><i class="fa-solid ${iconFor(level, item.slug)}"></i></span><span class="premium-card-copy"><b>${escapeHTML(item.name || item.title)}</b><small>${escapeHTML(subtitle || item.description || 'محتوى متاح داخل القسم المميز.')}</small>${extra}</span><i class="fa-solid fa-chevron-left"></i></button>`;
  const pushStep = () => history.pushState({ ...(history.state || {}), premiumStep: state.level, branch: state.branch, teacher: state.teacher, subject: state.subject }, '', location.href);
  const render = (data, level, heading, note, mapper, push) => { state.records = data; state.level = level; updateSteps(); title.textContent = heading; description.textContent = note; if (push) pushStep(); if (!data.length) return setEmpty(level === 'branch' ? 'لا توجد فروع متاحة' : level === 'teacher' ? 'لا يوجد أساتذة بعد' : level === 'subject' ? 'لا توجد مواد بعد' : 'لا توجد ملفات متاحة', 'سيضيف المشرف المحتوى من لوحة القسم المميز.'); grid.innerHTML = data.map(mapper).join(''); };

  async function loadBranches(push = false) { const args = { p_section_slug: 'baccalaureate' }; state.branch = null; state.teacher = null; state.subject = null; const cached = readCache('premium_list_branches', args); if (cached) render(cached, 'branch', 'اختر الفرع', 'ابدأ باختيار بكالوريا علمي أو بكالوريا أدبي.', item => card('branch', item, item.description), push); else setLoading(); try { const data = await rpc('premium_list_branches', args); render(data, 'branch', 'اختر الفرع', 'ابدأ باختيار بكالوريا علمي أو بكالوريا أدبي.', item => card('branch', item, item.description), push); } catch (error) { if (!cached) setEmpty('تعذر تحميل الفروع', friendlyError(error, 'تحقق من الاتصال ثم حاول مرة أخرى.')); } }
  async function loadTeachers(branch, push = true) { const args = { p_branch_id: branch.id }; state.branch = branch; state.teacher = null; state.subject = null; const cached = readCache('premium_list_teachers', args); if (cached) render(cached, 'teacher', branch.name, 'اختر الأستاذ للوصول إلى مواده وملفاته.', item => { const extra = item.bundle_enabled ? `<span class="premium-file-meta"><span class="premium-badge premium-price"><i class="fa-solid fa-layer-group"></i> كود شامل: ${escapeHTML(item.bundle_price)} ل.س</span></span>` : ''; return card('teacher', item, item.description || 'مواد وملفات الأستاذ ضمن القسم المميز.', extra); }, push); else setLoading(); try { const data = await rpc('premium_list_teachers', args); render(data, 'teacher', branch.name, 'اختر الأستاذ للوصول إلى مواده وملفاته.', item => { const extra = item.bundle_enabled ? `<span class="premium-file-meta"><span class="premium-badge premium-price"><i class="fa-solid fa-layer-group"></i> كود شامل: ${escapeHTML(item.bundle_price)} ل.س</span></span>` : ''; return card('teacher', item, item.description || 'مواد وملفات الأستاذ ضمن القسم المميز.', extra); }, push); } catch (error) { if (!cached) setEmpty('تعذر تحميل الأساتذة', friendlyError(error, 'حاول مرة أخرى.')); } }
  async function loadSubjects(teacher, push = true) { const args = { p_teacher_id: teacher.id }; state.teacher = teacher; state.subject = null; const cached = readCache('premium_list_subjects', args); if (cached) render(cached, 'subject', teacher.name, 'اختر المادة لاستعراض الملفات التابعة لها.', item => card('subject', item, item.description || 'المواد المتوفرة لهذا الأستاذ.'), push); else setLoading(); try { const data = await rpc('premium_list_subjects', args); render(data, 'subject', teacher.name, 'اختر المادة لاستعراض الملفات التابعة لها.', item => card('subject', item, item.description || 'المواد المتوفرة لهذا الأستاذ.'), push); } catch (error) { if (!cached) setEmpty('تعذر تحميل المواد', friendlyError(error, 'حاول مرة أخرى.')); } }
  async function loadFiles(subject, push = true) { const args = { p_subject_id: subject.id }; state.subject = subject; const cached = readCache('premium_list_files', args); if (cached) render(cached, 'file', subject.name, 'افتح الملف بعد التحقق من صلاحية الوصول.', item => { const extra = `<span class="premium-file-meta"><span class="premium-badge premium-price"><i class="fa-solid fa-tag"></i> كود الملف: ${escapeHTML(item.access_price)} ل.س</span>${item.bundle_enabled ? `<span class="premium-badge"><i class="fa-solid fa-layer-group"></i> شامل الأستاذ: ${escapeHTML(item.bundle_price)} ل.س</span>` : ''}</span>`; return card('file', item, item.description || 'ملف تعليمي محمي بصلاحية وصول.', extra); }, push); else setLoading(); try { const data = await rpc('premium_list_files', args); render(data, 'file', subject.name, 'افتح الملف بعد التحقق من صلاحية الوصول.', item => { const extra = `<span class="premium-file-meta"><span class="premium-badge premium-price"><i class="fa-solid fa-tag"></i> كود الملف: ${escapeHTML(item.access_price)} ل.س</span>${item.bundle_enabled ? `<span class="premium-badge"><i class="fa-solid fa-layer-group"></i> شامل الأستاذ: ${escapeHTML(item.bundle_price)} ل.س</span>` : ''}</span>`; return card('file', item, item.description || 'ملف تعليمي محمي بصلاحية وصول.', extra); }, push); } catch (error) { if (!cached) setEmpty('تعذر تحميل الملفات', friendlyError(error, 'حاول مرة أخرى.')); } }
  function directDriveDownloadUrl(rawUrl) { const value = String(rawUrl || '').trim(); if (!value) return value; try { const url = new URL(value); const host = url.hostname.toLowerCase(); if (host !== 'drive.google.com' && host !== 'docs.google.com' && host !== 'drive.usercontent.google.com') return value; let fileId = url.searchParams.get('id') || ''; const match = url.pathname.match(/\/file\/d\/([^/]+)/) || url.pathname.match(/\/document\/d\/([^/]+)/); if (!fileId && match) fileId = match[1]; if (!fileId) return value; return `https://drive.google.com/uc?export=download&id=${encodeURIComponent(fileId)}`; } catch { return value; } }
  function openNativePdf(url, documentTitle) { const bridge = window.NabdAndroid; if (!bridge || typeof bridge.openNativePdfViewer !== 'function') return false; try { bridge.openNativePdfViewer(url, documentTitle || 'ملف تعليمي', true); return true; } catch (error) { console.warn('تعذر فتح عارض PDF الأصلي', error); return false; } }
  async function openFile(fileId) { try { const rows = await rpc('premium_open_file', { p_file_id: fileId }); const result = rows[0]; if (result?.allowed && result.file_url) { const pdfUrl = directDriveDownloadUrl(result.file_url); if (openNativePdf(pdfUrl, result.file_title)) return; window.location.href = pdfUrl; return; } const file = state.records.find(item => item.id === fileId) || {}; showAccessModal(fileId, { ...file, file_title: result?.file_title || file.title }); } catch (error) { toast(friendlyError(error, 'تعذر التحقق من صلاحية الملف.')); } }
  function showAccessModal(fileId, file) { if (!modalHistoryEntry) { history.pushState({ ...(history.state || {}), premiumStep: state.level, branch: state.branch, teacher: state.teacher, subject: state.subject, premiumModal: 'access' }, '', location.href); modalHistoryEntry = true; } const teacher = state.teacher || {}; const whatsapp = file.whatsapp || teacher.whatsapp || ''; const singleLink = whatsappHref(whatsapp, `أرغب بشراء كود الملف: ${file.file_title || file.title || ''}`); const bundleLink = whatsappHref(whatsapp, `أرغب بشراء الكود الشامل للأستاذ: ${file.teacher_name || teacher.name || ''}`); openModal(`<div class="modal-head"><div><span class="eyebrow">صلاحية مطلوبة</span><h3>${escapeHTML(file.file_title || file.title || 'هذا الملف')}</h3></div><button class="close-modal" aria-label="إغلاق">×</button></div><div class="premium-modal-copy"><strong>هذا الملف محمي بكود وصول.</strong><br>فعّل الكود من حسابك لفتح الرابط الحقيقي. لا يتم إرسال الرابط قبل نجاح التحقق من قاعدة البيانات.</div><div class="premium-access-options"><div class="premium-access-option"><div><b>كود الملف المحدد</b><small>${escapeHTML(file.access_price ?? 0)} ل.س</small></div>${singleLink ? `<a class="primary-button" href="${singleLink}" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-whatsapp"></i> شراء</a>` : '<span class="premium-note">لم يضف المشرف رقم واتساب لهذا الأستاذ بعد.</span>'}</div>${file.bundle_enabled ? `<div class="premium-access-option"><div><b>كود شامل للأستاذ</b><small>${escapeHTML(file.bundle_price)} ل.س · يفتح كل ملفاته الحالية والمستقبلية</small></div>${bundleLink ? `<a class="primary-button" href="${bundleLink}" target="_blank" rel="noopener noreferrer"><i class="fa-brands fa-whatsapp"></i> شراء</a>` : '<span class="premium-note">لم يضف المشرف رقم واتساب لهذا الأستاذ بعد.</span>'}</div>` : ''}</div><form class="premium-code-form" id="premiumRedeemForm"><label>لديك كود وصول؟<input name="code" required autocomplete="off" placeholder="أدخل الكود هنا"></label><button class="primary-button" type="submit"><i class="fa-solid fa-unlock"></i> تفعيل الكود وفتح الملف</button><p class="premium-note">رقم واتساب الأستاذ: <span class="premium-whatsapp">${escapeHTML(whatsapp || 'غير محدد')}</span></p></form>`); $('#premiumRedeemForm')?.addEventListener('submit', async event => { event.preventDefault(); const code = String(new FormData(event.currentTarget).get('code') || '').trim(); const button = event.currentTarget.querySelector('button'); button.disabled = true; try { const rows = await rpc('premium_redeem_access_code', { p_code: code }); const response = rows[0]; if (!response?.success) throw new Error(response?.message || 'تعذر تفعيل الكود.'); closeModal(); toast(response.message || 'تم تفعيل الكود.'); await openFile(fileId); } catch (error) { toast(friendlyError(error, 'كود الوصول غير صالح.')); button.disabled = false; } }); }
  const restoreHistory = snapshot => { const step = snapshot?.premiumStep; if (step === 'teacher' && snapshot.branch) return loadTeachers(snapshot.branch, false); if (step === 'subject' && snapshot.teacher) return loadSubjects(snapshot.teacher, false); if (step === 'file' && snapshot.subject) return loadFiles(snapshot.subject, false); return loadBranches(false); };
  grid?.addEventListener('click', event => { const button = event.target.closest('[data-premium-id]'); if (!button) return; const item = state.records.find(entry => entry.id === button.dataset.premiumId); if (!item) return; if (state.level === 'branch') loadTeachers(item); else if (state.level === 'teacher') loadSubjects(item); else if (state.level === 'subject') loadFiles(item); else openFile(item.id); });
  back?.addEventListener('click', () => { if (modalHistoryEntry) return closeModal(); if (state.level !== 'branch') history.back(); });
  window.addEventListener('popstate', event => { if (modalHistoryEntry) { modalHistoryEntry = false; const { backdrop } = modal(); backdrop?.classList.remove('show'); document.body.classList.remove('sheet-open'); return; } if (event.state?.premiumStep) restoreHistory(event.state); });
  $('#modalBackdrop')?.addEventListener('click', event => { if (event.target === event.currentTarget) closeModal(); });
  if (!history.state?.premiumStep) history.replaceState({ ...(history.state || {}), premiumStep: 'branch' }, '', location.href);
  // ابدأ عرض القسم فورًا؛ فحص الجلسة وطلب البيانات لا يجب أن يحجبا الواجهة المشتركة.
  if (client) void loadBranches(false);
  else if (grid) setEmpty('القسم المميز غير متاح محليًا', 'تحقق من الاتصال ثم أعد المحاولة.');
})();
