(() => {
  'use strict';
  const client = window.nabdSupabase;
  const $ = selector => document.querySelector(selector);
  const state = { catalog: { branches: [], teachers: [], subjects: [], files: [], codes: [], settings: {} }, editing: {} };
  const escapeHTML = value => String(value ?? '').replace(/[&<>'"]/g, char => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', "'": '&#39;', '"': '&quot;' }[char]));
  const toast = text => { const node = $('#toast'); if (!node) return; node.textContent = text; node.classList.add('show'); clearTimeout(window.premiumAdminToast); window.premiumAdminToast = setTimeout(() => node.classList.remove('show'), 3200); };
  const rpc = async (name, args = {}) => { const result = await client.rpc(name, args); if (result.error) throw result.error; return result.data; };
  const formData = form => Object.fromEntries(new FormData(form).entries());
  const uuidOrNull = value => value || null;
  const numberOrZero = value => Number.isFinite(Number(value)) ? Number(value) : 0;
  const bool = value => value === true || value === 'on' || value === 'true';
  const dateOrNull = value => value ? new Date(value).toISOString() : null;
  function showWorkspace(allowed) { $('#premiumAdminGate')?.classList.toggle('hidden', allowed); $('#premiumAdminWorkspace')?.classList.toggle('hidden', !allowed); }
  function branchName(id) { return state.catalog.branches.find(item => item.id === id)?.name || 'فرع غير محدد'; }
  function teacherName(id) { return state.catalog.teachers.find(item => item.id === id)?.name || 'أستاذ غير محدد'; }
  function subjectName(id) { return state.catalog.subjects.find(item => item.id === id)?.name || 'مادة غير محددة'; }
  function fillSelect(selector, items, placeholder, selected = '') { const node = $(selector); if (!node) return; node.innerHTML = `<option value="">${escapeHTML(placeholder)}</option>${items.map(item => `<option value="${escapeHTML(item.id)}" ${item.id === selected ? 'selected' : ''}>${escapeHTML(item.name || item.title)}</option>`).join('')}`; }
  function renderLists() {
    const branches = $('#adminBranchesList'); if (branches) branches.innerHTML = state.catalog.branches.map(item => listItem(item.name, `${item.slug} · ${item.description || 'دون وصف'}`, 'branch', item.id)).join('') || empty('لا توجد فروع.');
    const teachers = $('#adminTeachersList'); if (teachers) teachers.innerHTML = state.catalog.teachers.map(item => listItem(item.name, `${branchName(item.branch_id)} · ${item.whatsapp ? `واتساب: ${item.whatsapp}` : 'واتساب غير محدد'} · ${item.bundle_enabled ? `كود شامل ${item.bundle_price}` : 'بدون كود شامل'}`, 'teacher', item.id)).join('') || empty('لا يوجد أساتذة.');
    const subjects = $('#adminSubjectsList'); if (subjects) subjects.innerHTML = state.catalog.subjects.map(item => listItem(item.name, `${teacherName(item.teacher_id)} · ${item.description || 'دون وصف'}`, 'subject', item.id)).join('') || empty('لا توجد مواد.');
    const files = $('#adminFilesList'); if (files) files.innerHTML = state.catalog.files.map(item => listItem(item.title, `${subjectName(item.subject_id)} · ${item.access_price} ل.س · ${item.is_available ? 'متاح' : 'مخفي'}`, 'file', item.id)).join('') || empty('لا توجد ملفات.');
    const codes = $('#adminCodesList'); if (codes) codes.innerHTML = state.catalog.codes.map(item => listItem(`${item.code_type === 'file' ? 'ملف' : 'شامل'} · ****${item.code_hint}`, `${item.code_type === 'file' ? subjectName(state.catalog.files.find(file => file.id === item.file_id)?.subject_id) : teacherName(item.teacher_id)} · ${item.uses_count}/${item.max_uses || '∞'} استخدام · ${item.is_active ? 'فعال' : 'معطل'}`, 'code', item.id, false, item.is_active)).join('') || empty('لا توجد أكواد منشأة.');
  }
  function empty(text) { return `<div class="premium-admin-status">${escapeHTML(text)}</div>`; }
  function listItem(title, meta, type, id, editable = true, active = true) { const actions = editable ? `<button type="button" data-edit="${type}" data-id="${escapeHTML(id)}" title="تعديل"><i class="fa-solid fa-pen"></i></button><button class="danger" type="button" data-delete="${type}" data-id="${escapeHTML(id)}" title="حذف"><i class="fa-solid fa-trash"></i></button>` : type === 'code' ? `<button type="button" data-toggle-code="${escapeHTML(id)}" data-active="${active}" title="${active ? 'تعطيل' : 'تفعيل'}"><i class="fa-solid ${active ? 'fa-toggle-on' : 'fa-toggle-off'}"></i></button><button class="danger" type="button" data-delete="code" data-id="${escapeHTML(id)}" title="حذف"><i class="fa-solid fa-trash"></i></button>` : `<button class="danger" type="button" data-delete="${type}" data-id="${escapeHTML(id)}" title="حذف"><i class="fa-solid fa-trash"></i></button>`; return `<div class="premium-admin-list-item"><div><b>${escapeHTML(title)}</b><small>${escapeHTML(meta)}</small></div><div class="premium-admin-list-actions">${actions}</div></div>`; }
  function refreshSelects() { fillSelect('#teacherBranch', state.catalog.branches, 'اختر الفرع'); fillSelect('#subjectTeacher', state.catalog.teachers, 'اختر الأستاذ'); fillSelect('#fileSubject', state.catalog.subjects, 'اختر المادة'); fillSelect('#codeFile', state.catalog.files, 'اختر الملف'); fillSelect('#codeTeacher', state.catalog.teachers, 'اختر الأستاذ'); }
  async function loadCatalog() { const data = await rpc('premium_admin_get_catalog'); state.catalog = { branches: data.branches || [], teachers: data.teachers || [], subjects: data.subjects || [], files: data.files || [], codes: data.codes || [], settings: data.settings || {} }; refreshSelects(); renderLists(); const settings = $('#settingsForm'); if (settings) settings.default_whatsapp.value = state.catalog.settings.default_whatsapp || ''; }
  function setForm(formId, item) { const form = $('#' + formId); if (!form) return; Object.entries(item || {}).forEach(([key, value]) => { const field = form.elements.namedItem(key); if (!field) return; if (field.type === 'checkbox') field.checked = Boolean(value); else field.value = value ?? ''; }); }
  function resetForm(formId) { const form = $('#' + formId); if (!form) return; form.reset(); const id = form.elements.namedItem('id'); if (id) id.value = ''; if (formId === 'fileForm' && form.elements.namedItem('is_available')) form.elements.namedItem('is_available').checked = true; }
  async function saveBranch(form) { const data = formData(form); await rpc('premium_admin_upsert_branch', { p_id: uuidOrNull(data.id), p_section_slug: 'baccalaureate', p_slug: data.slug.trim(), p_name: data.name.trim(), p_description: data.description.trim(), p_sort_order: numberOrZero(data.sort_order), p_is_active: true }); }
  async function saveTeacher(form) { const data = formData(form); await rpc('premium_admin_upsert_teacher', { p_id: uuidOrNull(data.id), p_branch_id: data.branch_id, p_name: data.name.trim(), p_description: data.description.trim(), p_avatar_url: data.avatar_url.trim() || null, p_bundle_enabled: bool(data.bundle_enabled), p_bundle_price: numberOrZero(data.bundle_price), p_whatsapp: data.whatsapp.trim() || null, p_sort_order: numberOrZero(data.sort_order), p_is_active: true }); }
  async function saveSubject(form) { const data = formData(form); await rpc('premium_admin_upsert_subject', { p_id: uuidOrNull(data.id), p_teacher_id: data.teacher_id, p_name: data.name.trim(), p_description: data.description.trim(), p_sort_order: numberOrZero(data.sort_order), p_is_active: true }); }
  async function saveFile(form) { const data = formData(form); await rpc('premium_admin_upsert_file', { p_id: uuidOrNull(data.id), p_subject_id: data.subject_id, p_title: data.title.trim(), p_description: data.description.trim(), p_file_url: data.file_url.trim(), p_access_price: numberOrZero(data.access_price), p_is_available: bool(data.is_available), p_sort_order: numberOrZero(data.sort_order) }); }
  async function saveCode(form) { const data = formData(form); const rows = await rpc('premium_admin_upsert_code', { p_code: data.code.trim() || null, p_code_type: data.code_type, p_file_id: data.code_type === 'file' ? uuidOrNull(data.file_id) : null, p_teacher_id: data.code_type === 'teacher_bundle' ? uuidOrNull(data.teacher_id) : null, p_price: numberOrZero(data.price), p_max_uses: Math.max(0, parseInt(data.max_uses || '1', 10)), p_expires_at: dateOrNull(data.expires_at) }); const generated = rows?.[0]; if (generated?.code) { const box = $('#generatedCode'); box.classList.remove('hidden'); box.innerHTML = `<div class="premium-admin-code"><code>${escapeHTML(generated.code)}</code><button type="button" id="copyGeneratedCode">نسخ</button></div><p class="premium-admin-status">احفظ هذا الكود الآن؛ لن يتم عرض قيمته الكاملة مرة أخرى.</p>`; $('#copyGeneratedCode')?.addEventListener('click', async () => { await navigator.clipboard?.writeText(generated.code); toast('تم نسخ الكود.'); }); } }
  async function saveSettings(form) { const data = formData(form); await rpc('premium_admin_update_settings', { p_whatsapp: data.default_whatsapp.trim() }); }
  async function deleteEntity(type, id) { if (!window.confirm('هل تريد حذف هذا العنصر؟ سيؤثر الحذف في العناصر التابعة له.')) return; await rpc('premium_admin_delete_entity', { p_entity: type, p_id: id }); toast('تم الحذف.'); await loadCatalog(); }
  async function toggleCode(button) { button.disabled = true; try { const active = button.dataset.active !== 'true'; await rpc('premium_admin_set_code_active', { p_id: button.dataset.toggleCode, p_is_active: active }); toast(active ? 'تم تفعيل الكود.' : 'تم تعطيل الكود.'); await loadCatalog(); } catch (error) { toast(error.message || 'تعذر تحديث حالة الكود.'); button.disabled = false; } }
  function bindTabs() { $('#premiumAdminTabs')?.addEventListener('click', event => { const button = event.target.closest('[data-admin-pane]'); if (!button) return; document.querySelectorAll('#premiumAdminTabs button').forEach(item => item.classList.toggle('active', item === button)); document.querySelectorAll('[data-admin-pane-view]').forEach(pane => pane.classList.toggle('active', pane.dataset.adminPaneView === button.dataset.adminPane)); }); }
  function bindForms() { const handlers = { branchForm: saveBranch, teacherForm: saveTeacher, subjectForm: saveSubject, fileForm: saveFile, codeForm: saveCode, settingsForm: saveSettings }; Object.entries(handlers).forEach(([id, handler]) => $('#' + id)?.addEventListener('submit', async event => { event.preventDefault(); const button = event.currentTarget.querySelector('button[type="submit"]'); if (button) button.disabled = true; try { await handler(event.currentTarget); if (id !== 'codeForm') { resetForm(id); await loadCatalog(); toast('تم الحفظ بنجاح.'); } else { await loadCatalog(); toast('تم إنشاء الكود.'); } } catch (error) { toast(error.message || 'تعذر تنفيذ العملية.'); } finally { if (button) button.disabled = false; } })); document.querySelectorAll('[data-reset-form]').forEach(button => button.addEventListener('click', () => resetForm(button.dataset.resetForm))); $('#codeType')?.addEventListener('change', event => { const bundle = event.target.value === 'teacher_bundle'; $('#codeFileWrap')?.classList.toggle('hidden', bundle); $('#codeTeacherWrap')?.classList.toggle('hidden', !bundle); }); }
  function bindLists() { document.body.addEventListener('click', event => { const toggle = event.target.closest('[data-toggle-code]'); if (toggle) { toggleCode(toggle); return; } const edit = event.target.closest('[data-edit]'); if (edit) { const type = edit.dataset.edit; const collections = { branch: 'branches', teacher: 'teachers', subject: 'subjects', file: 'files' }; const item = state.catalog[collections[type]]?.find(entry => entry.id === edit.dataset.id); const forms = { branch: 'branchForm', teacher: 'teacherForm', subject: 'subjectForm', file: 'fileForm' }; if (item && forms[type]) { setForm(forms[type], item); document.querySelector(`[data-admin-pane="${collections[type]}"]`)?.click(); window.scrollTo({ top: 0, behavior: 'smooth' }); } return; } const remove = event.target.closest('[data-delete]'); if (remove) deleteEntity(remove.dataset.delete, remove.dataset.id); }); }
  async function init() { if (!client) return; try { const allowed = await rpc('premium_is_admin'); if (!allowed) { showWorkspace(false); $('#premiumAdminGate').innerHTML = '<i class="fa-solid fa-lock"></i><h2>لا تملك صلاحية الوصول</h2><p>هذه الصفحة مخصصة للمشرفين المعتمدين في قاعدة البيانات.</p>'; return; } showWorkspace(true); bindTabs(); bindForms(); bindLists(); await loadCatalog(); } catch (error) { showWorkspace(false); $('#premiumAdminGate').innerHTML = `<i class="fa-solid fa-triangle-exclamation"></i><h2>تعذر التحقق من الصلاحية</h2><p>${escapeHTML(error.message || 'حاول تسجيل الدخول من جديد.')}</p>`; } }
  document.addEventListener('DOMContentLoaded', init);
})();
