-- Enforce chat shutdown and account bans at database level.
create table if not exists public.chat_user_bans (user_id uuid primary key references auth.users(id) on delete cascade, banned_by uuid not null references auth.users(id), reason text, created_at timestamptz not null default now(), expires_at timestamptz);
create index if not exists chat_user_bans_expires_idx on public.chat_user_bans(expires_at);
alter table public.chat_user_bans enable row level security;
create or replace function public.chat_can_send_public() returns boolean language sql stable security definer set search_path=public,private,pg_temp as $$ select auth.uid() is not null and exists(select 1 from public.chat_platform_settings where id=true and enabled=true) and not exists(select 1 from public.chat_user_bans where user_id=auth.uid() and (expires_at is null or expires_at>now())); $$;
drop policy if exists "public chat insert own" on public.public_chat_messages;
create policy "public chat insert own" on public.public_chat_messages for insert to authenticated with check (sender_id=auth.uid() and public.chat_can_send_public());
create or replace function public.chat_moderate_delete_message(p_message uuid) returns boolean language plpgsql security definer set search_path=public,private,pg_temp as $$ begin if not public.chat_can_moderate() then raise exception 'لا تملك صلاحية حذف الرسائل'; end if; update public.public_chat_messages set deleted_at=now() where id=p_message and deleted_at is null; return found; end; $$;
create or replace function public.chat_admin_ban_user(p_user_ref text,p_banned boolean default true,p_reason text default null,p_expires_at timestamptz default null) returns boolean language plpgsql security definer set search_path=public,private,pg_temp as $$ declare v_user uuid; begin if not public.chat_can_moderate() then raise exception 'لا تملك صلاحية حظر الحسابات'; end if; begin v_user:=p_user_ref::uuid; exception when others then select id into v_user from auth.users where lower(email)=lower(trim(p_user_ref)) limit 1; end; if v_user is null then raise exception 'لم يتم العثور على المستخدم'; end if; if v_user=auth.uid() then raise exception 'لا يمكنك حظر حسابك الحالي'; end if; if p_banned then insert into public.chat_user_bans(user_id,banned_by,reason,expires_at) values(v_user,auth.uid(),nullif(trim(p_reason),''),p_expires_at) on conflict(user_id) do update set banned_by=excluded.banned_by,reason=excluded.reason,expires_at=excluded.expires_at; else delete from public.chat_user_bans where user_id=v_user; end if; return true; end; $$;
grant execute on function public.chat_can_send_public() to authenticated;
grant execute on function public.chat_moderate_delete_message(uuid) to authenticated;
grant execute on function public.chat_admin_ban_user(text,boolean,text,timestamptz) to authenticated;
