revoke execute on function private.is_premium_admin() from public, anon, authenticated;
revoke execute on function public.premium_is_admin() from public, anon;
revoke execute on function public.premium_list_branches(text) from public, anon;
revoke execute on function public.premium_list_teachers(uuid) from public, anon;
revoke execute on function public.premium_list_subjects(uuid) from public, anon;
revoke execute on function public.premium_list_files(uuid) from public, anon;
revoke execute on function public.premium_check_file_access(uuid) from public, anon;
revoke execute on function public.premium_open_file(uuid) from public, anon;
revoke execute on function public.premium_redeem_access_code(text) from public, anon;
revoke execute on function public.premium_admin_get_catalog() from public, anon;
revoke execute on function public.premium_admin_upsert_branch(uuid,text,text,text,text,integer,boolean) from public, anon;
revoke execute on function public.premium_admin_upsert_teacher(uuid,uuid,text,text,text,boolean,numeric,text,integer,boolean) from public, anon;
revoke execute on function public.premium_admin_upsert_subject(uuid,uuid,text,text,integer,boolean) from public, anon;
revoke execute on function public.premium_admin_upsert_file(uuid,uuid,text,text,text,numeric,boolean,integer) from public, anon;
revoke execute on function public.premium_admin_upsert_code(text,text,uuid,uuid,numeric,integer,timestamptz) from public, anon;
revoke execute on function public.premium_admin_delete_entity(text,uuid) from public, anon;
revoke execute on function public.premium_admin_update_settings(text) from public, anon;
revoke execute on function public.premium_admin_set_code_active(uuid,boolean) from public, anon;
grant execute on function public.premium_is_admin() to authenticated;
grant execute on function public.premium_list_branches(text) to authenticated;
grant execute on function public.premium_list_teachers(uuid) to authenticated;
grant execute on function public.premium_list_subjects(uuid) to authenticated;
grant execute on function public.premium_list_files(uuid) to authenticated;
grant execute on function public.premium_check_file_access(uuid) to authenticated;
grant execute on function public.premium_open_file(uuid) to authenticated;
grant execute on function public.premium_redeem_access_code(text) to authenticated;
grant execute on function public.premium_admin_get_catalog() to authenticated;
grant execute on function public.premium_admin_upsert_branch(uuid,text,text,text,text,integer,boolean) to authenticated;
grant execute on function public.premium_admin_upsert_teacher(uuid,uuid,text,text,text,boolean,numeric,text,integer,boolean) to authenticated;
grant execute on function public.premium_admin_upsert_subject(uuid,uuid,text,text,integer,boolean) to authenticated;
grant execute on function public.premium_admin_upsert_file(uuid,uuid,text,text,text,numeric,boolean,integer) to authenticated;
grant execute on function public.premium_admin_upsert_code(text,text,uuid,uuid,numeric,integer,timestamptz) to authenticated;
grant execute on function public.premium_admin_delete_entity(text,uuid) to authenticated;
grant execute on function public.premium_admin_update_settings(text) to authenticated;
grant execute on function public.premium_admin_set_code_active(uuid,boolean) to authenticated;
